"""Pydantic schema package — generated from ``../../../openapi.yaml``.

The actual type definitions live in :mod:`flickies.schema._generated`,
which is regenerated by ``scripts/generate_models.sh`` (``make generate``)
every time the OpenAPI spec changes.

**Do NOT hand-edit ``_generated.py``** — edits get clobbered. To change
a request/response shape, edit ``openapi.yaml`` then run ``make generate``.

This wrapper module is hand-written and exposes:

  - re-exports of every generated class (so handler code does
    ``from flickies.schema import VideoLipsyncRequest`` and doesn't
    care about the split)
  - runtime helpers: ``validate_input_xor`` / ``validate_output_xor``
    (enforced at handler boundary — Pydantic's ``oneOf`` JSON Schema
    construct doesn't survive datamodel-codegen inheritance, so the YAML
    keeps both fields nullable and these helpers enforce the xor)
  - ``url_to_str`` to coerce ``AnyUrl`` → ``str | None``
"""
from __future__ import annotations

from fastapi import HTTPException

# The generated module is committed to git. Tests / dev environments that
# don't have it yet will see an ImportError — run `make generate` to seed it.
try:
    from ._generated import *  # noqa: F401,F403
except ImportError:  # pragma: no cover
    pass


def url_to_str(url) -> str | None:
    """Coerce a Pydantic ``AnyUrl`` to a plain string. Returns None for None."""
    if url is None:
        return None
    return str(url)


def validate_input_xor(file_path: str | None, file_url) -> None:
    """Enforce exactly one of file_path / file_url. HTTPException(400) on violation."""
    n = int(bool(file_path)) + int(bool(file_url))
    if n == 0:
        raise HTTPException(
            status_code=400,
            detail="must provide exactly one of: file_path, file_url",
        )
    if n > 1:
        raise HTTPException(
            status_code=400,
            detail="file_path and file_url are mutually exclusive",
        )


def validate_output_xor(
    output_path: str | None,
    output_url,
    *,
    async_job: bool,
) -> None:
    """Enforce output destination on a video-producing endpoint.

    - sync mode: exactly one of output_path / output_url is required
    - async mode: both optional (server auto-generates jobs/{id}.{ext})

    Providing BOTH is always rejected as mutually exclusive.
    """
    has_path = bool(output_path)
    has_url = bool(output_url)
    if has_path and has_url:
        raise HTTPException(
            status_code=400,
            detail="output_path and output_url are mutually exclusive",
        )
    if async_job:
        return
    if not has_path and not has_url:
        raise HTTPException(
            status_code=400,
            detail=(
                "video-producing endpoint requires output_path or output_url "
                "(sync mode); use async_job=true for auto-staged jobs/{id}.{ext}"
            ),
        )
