# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-21T19:28:18+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AnyUrl, BaseModel, Field


class ErrorBody(BaseModel):
    code: Annotated[
        str,
        Field(
            description='Machine-readable UPPER_SNAKE_CASE error code.',
            examples=[
                'BAD_REQUEST',
                'UNAUTHORIZED',
                'NOT_FOUND',
                'NONCOMMERCIAL_GATE_REFUSED',
                'VALIDATION_FAILED',
                'INTERNAL_SERVER_ERROR',
            ],
        ),
    ]
    message: Annotated[str, Field(description='Human-readable error description.')]
    details: Annotated[
        dict[str, Any] | None,
        Field(
            description='Optional structured detail bag — field-by-field validation errors, upstream provider IDs, etc.'
        ),
    ] = None


class HealthResponse(BaseModel):
    status: Annotated[str, Field(examples=['ok'])]
    version: str
    device: Annotated[str, Field(description='auto / cpu / cuda')]
    available_engines: list[str]
    enabled_engines: list[str] | None = None
    loaded_engine: Annotated[
        str | None,
        Field(description='Currently resident engine slug, or null if none loaded.'),
    ] = None
    noncommercial_enabled: bool


class EngineInfo(BaseModel):
    slug: str
    executor: str
    variant: str | None = None
    loaded: bool
    noncommercial: bool
    cuda_only: bool | None = None
    vram_gb_min: float | None = None
    description: str | None = None
    last_used_secs_ago: Annotated[
        float | None,
        Field(
            description='Seconds since this engine last served a request; null if never used.'
        ),
    ] = None


class EngineList(BaseModel):
    engines: list[EngineInfo]


class JobAcceptedResponse(BaseModel):
    job_id: UUID
    status: Annotated[str, Field(examples=['accepted'])]


class Status(StrEnum):
    pending = 'pending'
    running = 'running'
    complete = 'complete'
    failed = 'failed'
    cancelled = 'cancelled'


class Error(BaseModel):
    code: str | None = None
    message: str | None = None


class JobStatusResponse(BaseModel):
    job_id: UUID
    status: Status
    result: dict[str, Any] | None = None
    error: Error | None = None


class StagedOutputResponse(BaseModel):
    path: str
    size: int
    sha256: str | None = None
    duration_sec: float | None = None
    width: int | None = None
    height: int | None = None


class UrlOutputResponse(BaseModel):
    url: AnyUrl
    size: int
    sha256: str | None = None


class BaseVideoInputRequest(BaseModel):
    file_path: Annotated[
        str | None,
        Field(description='FILES_DIR-relative path of an already-uploaded video.'),
    ] = None
    file_url: Annotated[
        AnyUrl | None, Field(description='HTTP(S) URL the server fetches.')
    ] = None


class OutputFormat(StrEnum):
    mp4 = 'mp4'
    webm = 'webm'
    mov = 'mov'
    mkv = 'mkv'


class BaseVideoOutputRequest(BaseModel):
    output_path: str | None = None
    output_url: AnyUrl | None = None
    async_job: bool = False
    webhook_url: Annotated[
        AnyUrl | None,
        Field(description='Notify URL on async completion (HMAC-signed).'),
    ] = None
    output_format: OutputFormat = 'mp4'


class Engine(StrEnum):
    wav2lip = 'wav2lip'
    wav2lip_gan = 'wav2lip-gan'
    latentsync_1_5 = 'latentsync-1.5'


class VideoLipsyncRequest(BaseVideoOutputRequest):
    face_path: Annotated[
        str | None, Field(description='FILES_DIR-relative face video or still image.')
    ] = None
    face_url: AnyUrl | None = None
    audio_path: Annotated[
        str | None,
        Field(
            description='FILES_DIR-relative path of the driving audio (wav/mp3/m4a).'
        ),
    ] = None
    audio_url: Annotated[
        AnyUrl | None, Field(description='http(s) URL of the driving audio.')
    ] = None
    engine: Annotated[
        Engine,
        Field(
            description='wav2lip / wav2lip-gan require FLICKIES_ENABLE_NONCOMMERCIAL=1\n(LRS2 training data is non-commercial). latentsync-1.5 is the\ncommercial-safe default on CUDA.\n'
        ),
    ] = 'latentsync-1.5'
    restore_face: Annotated[
        bool,
        Field(
            description='Chain GFPGAN over the output to clean up the face region (recommended after wav2lip*).'
        ),
    ] = False


class VideoRestoreRequest(BaseVideoInputRequest, BaseVideoOutputRequest):
    engine: Literal['gfpgan'] = 'gfpgan'


class VideoTrimRequest(BaseVideoInputRequest, BaseVideoOutputRequest):
    start_sec: Annotated[float, Field(ge=0.0)]
    end_sec: Annotated[float, Field(ge=0.0)]


class VideoConcatRequest(BaseVideoOutputRequest):
    inputs_paths: Annotated[list[str] | None, Field(min_length=2)] = None
    inputs_urls: Annotated[list[AnyUrl] | None, Field(min_length=2)] = None


class PaletteMode(StrEnum):
    full = 'full'
    diff = 'diff'
    single = 'single'


class GifOptions(BaseModel):
    width: int | None = None
    loop: Annotated[int, Field(description='0 = infinite')] = 0
    palette_mode: PaletteMode = 'full'


class VideoTranscodeRequest(BaseVideoInputRequest, BaseVideoOutputRequest):
    video_codec: Annotated[
        str | None, Field(examples=['libx264', 'libx265', 'libvpx-vp9', 'libaom-av1'])
    ] = None
    audio_codec: Annotated[str | None, Field(examples=['aac', 'libopus', 'copy'])] = (
        None
    )
    crf: Annotated[int | None, Field(ge=0, le=51)] = None
    preset: Annotated[
        str | None, Field(examples=['ultrafast', 'fast', 'medium', 'slow'])
    ] = None
    fps: Annotated[
        float | None,
        Field(
            description='Re-encode at this frame rate. Applies to all output formats.',
            ge=1.0,
            le=240.0,
        ),
    ] = None
    gif_options: Annotated[
        GifOptions | None, Field(description='Only consulted when output_format=gif.')
    ] = None


class VideoScaleRequest(BaseVideoInputRequest, BaseVideoOutputRequest):
    width: Annotated[int, Field(ge=16)]
    height: Annotated[int, Field(ge=16)]
    keep_aspect: Annotated[
        bool, Field(description='If true, pad/crop to maintain source aspect.')
    ] = True


class VideoMuxAudioRequest(BaseVideoOutputRequest):
    video_path_or_url: str
    audio_path_or_url: str
    replace_existing_audio: bool = True


class AudioFormat(StrEnum):
    wav = 'wav'
    mp3 = 'mp3'
    m4a = 'm4a'
    ogg = 'ogg'
    flac = 'flac'


class VideoExtractAudioRequest(BaseVideoInputRequest):
    audio_format: AudioFormat = 'wav'
    output_path: str | None = None
    output_url: AnyUrl | None = None


class VideoThumbnailGridRequest(BaseVideoInputRequest):
    rows: Annotated[int, Field(ge=1, le=16)]
    cols: Annotated[int, Field(ge=1, le=16)]
    cell_width: int = 320
    cell_height: int = 180
    output_path: str | None = None
    output_url: AnyUrl | None = None


class VideoInfoRequest(BaseVideoInputRequest):
    pass


class VideoInfoResponse(BaseModel):
    duration_sec: float | None = None
    width: int | None = None
    height: int | None = None
    fps: float | None = None
    video_codec: str | None = None
    audio_codec: str | None = None
    bitrate: int | None = None
    container_format: str | None = None
    size_bytes: int | None = None
