// Package flickiesclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package flickiesclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for BaseVideoOutputRequestOutputFormat.
const (
	BaseVideoOutputRequestOutputFormatMkv  BaseVideoOutputRequestOutputFormat = "mkv"
	BaseVideoOutputRequestOutputFormatMov  BaseVideoOutputRequestOutputFormat = "mov"
	BaseVideoOutputRequestOutputFormatMp4  BaseVideoOutputRequestOutputFormat = "mp4"
	BaseVideoOutputRequestOutputFormatWebm BaseVideoOutputRequestOutputFormat = "webm"
)

// Defines values for JobStatusResponseStatus.
const (
	Cancelled JobStatusResponseStatus = "cancelled"
	Complete  JobStatusResponseStatus = "complete"
	Failed    JobStatusResponseStatus = "failed"
	Pending   JobStatusResponseStatus = "pending"
	Running   JobStatusResponseStatus = "running"
)

// Defines values for VideoRestoreRequestOutputFormat.
const (
	VideoRestoreRequestOutputFormatMkv  VideoRestoreRequestOutputFormat = "mkv"
	VideoRestoreRequestOutputFormatMov  VideoRestoreRequestOutputFormat = "mov"
	VideoRestoreRequestOutputFormatMp4  VideoRestoreRequestOutputFormat = "mp4"
	VideoRestoreRequestOutputFormatWebm VideoRestoreRequestOutputFormat = "webm"
)

// Defines values for VideoScaleRequestOutputFormat.
const (
	VideoScaleRequestOutputFormatMkv  VideoScaleRequestOutputFormat = "mkv"
	VideoScaleRequestOutputFormatMov  VideoScaleRequestOutputFormat = "mov"
	VideoScaleRequestOutputFormatMp4  VideoScaleRequestOutputFormat = "mp4"
	VideoScaleRequestOutputFormatWebm VideoScaleRequestOutputFormat = "webm"
)

// Defines values for VideoTranscodeRequestOutputFormat.
const (
	VideoTranscodeRequestOutputFormatMkv  VideoTranscodeRequestOutputFormat = "mkv"
	VideoTranscodeRequestOutputFormatMov  VideoTranscodeRequestOutputFormat = "mov"
	VideoTranscodeRequestOutputFormatMp4  VideoTranscodeRequestOutputFormat = "mp4"
	VideoTranscodeRequestOutputFormatWebm VideoTranscodeRequestOutputFormat = "webm"
)

// Defines values for VideoTrimRequestOutputFormat.
const (
	Mkv  VideoTrimRequestOutputFormat = "mkv"
	Mov  VideoTrimRequestOutputFormat = "mov"
	Mp4  VideoTrimRequestOutputFormat = "mp4"
	Webm VideoTrimRequestOutputFormat = "webm"
)

// BaseVideoInputRequest Exactly one of file_path / file_url MUST be provided. Enforced at handler boundary.
type BaseVideoInputRequest struct {
	// FilePath FILES_DIR-relative path of an already-uploaded video.
	FilePath *string `json:"file_path"`

	// FileUrl HTTP(S) URL the server fetches.
	FileUrl *string `json:"file_url"`
}

// BaseVideoOutputRequest Exactly one of output_path / output_url required in sync mode; both optional in async mode (auto-staged).
type BaseVideoOutputRequest struct {
	AsyncJob     *bool                               `json:"async_job,omitempty"`
	OutputFormat *BaseVideoOutputRequestOutputFormat `json:"output_format,omitempty"`
	OutputPath   *string                             `json:"output_path"`
	OutputUrl    *string                             `json:"output_url"`

	// WebhookUrl Notify URL on async completion (HMAC-signed).
	WebhookUrl *string `json:"webhook_url"`
}

// BaseVideoOutputRequestOutputFormat defines model for BaseVideoOutputRequest.OutputFormat.
type BaseVideoOutputRequestOutputFormat string

// EngineInfo defines model for EngineInfo.
type EngineInfo struct {
	CudaOnly    *bool   `json:"cuda_only,omitempty"`
	Description *string `json:"description,omitempty"`
	Executor    string  `json:"executor"`

	// LastUsedSecsAgo Seconds since this engine last served a request; null if never used.
	LastUsedSecsAgo *float32 `json:"last_used_secs_ago"`
	Loaded          bool     `json:"loaded"`
	Noncommercial   bool     `json:"noncommercial"`
	Slug            string   `json:"slug"`
	Variant         *string  `json:"variant"`
	VramGbMin       *float32 `json:"vram_gb_min"`
}

// EngineList defines model for EngineList.
type EngineList struct {
	Engines []EngineInfo `json:"engines"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	// Code Machine-readable UPPER_SNAKE_CASE error code.
	Code string `json:"code"`

	// Details Optional structured detail bag — field-by-field validation errors, upstream provider IDs, etc.
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable error description.
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	AvailableEngines []string `json:"available_engines"`

	// Device auto / cpu / cuda
	Device         string    `json:"device"`
	EnabledEngines *[]string `json:"enabled_engines,omitempty"`

	// LoadedEngine Currently resident engine slug, or null if none loaded.
	LoadedEngine         *string `json:"loaded_engine"`
	NoncommercialEnabled bool    `json:"noncommercial_enabled"`
	Status               string  `json:"status"`
	Version              string  `json:"version"`
}

// JobAcceptedResponse defines model for JobAcceptedResponse.
type JobAcceptedResponse struct {
	JobId  openapi_types.UUID `json:"job_id"`
	Status string             `json:"status"`
}

// JobStatusResponse defines model for JobStatusResponse.
type JobStatusResponse struct {
	Error *struct {
		Code    *string `json:"code,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"error"`
	JobId  openapi_types.UUID      `json:"job_id"`
	Result *map[string]interface{} `json:"result"`
	Status JobStatusResponseStatus `json:"status"`
}

// JobStatusResponseStatus defines model for JobStatusResponse.Status.
type JobStatusResponseStatus string

// StagedOutputResponse defines model for StagedOutputResponse.
type StagedOutputResponse struct {
	DurationSec *float32 `json:"duration_sec"`
	Height      *int     `json:"height"`
	Path        string   `json:"path"`
	Sha256      *string  `json:"sha256"`
	Size        int      `json:"size"`
	Width       *int     `json:"width"`
}

// UrlOutputResponse defines model for UrlOutputResponse.
type UrlOutputResponse struct {
	Sha256 *string `json:"sha256"`
	Size   int     `json:"size"`
	Url    string  `json:"url"`
}

// VideoConcatRequest Exactly one of output_path / output_url required in sync mode; both optional in async mode (auto-staged).
type VideoConcatRequest = BaseVideoOutputRequest

// VideoExtractAudioRequest Exactly one of file_path / file_url MUST be provided. Enforced at handler boundary.
type VideoExtractAudioRequest = BaseVideoInputRequest

// VideoInfoRequest Exactly one of file_path / file_url MUST be provided. Enforced at handler boundary.
type VideoInfoRequest = BaseVideoInputRequest

// VideoInfoResponse defines model for VideoInfoResponse.
type VideoInfoResponse struct {
	AudioCodec      *string  `json:"audio_codec"`
	Bitrate         *int     `json:"bitrate"`
	ContainerFormat *string  `json:"container_format"`
	DurationSec     *float32 `json:"duration_sec,omitempty"`
	Fps             *float32 `json:"fps,omitempty"`
	Height          *int     `json:"height,omitempty"`
	SizeBytes       *int     `json:"size_bytes,omitempty"`
	VideoCodec      *string  `json:"video_codec,omitempty"`
	Width           *int     `json:"width,omitempty"`
}

// VideoLipsyncRequest Exactly one of output_path / output_url required in sync mode; both optional in async mode (auto-staged).
type VideoLipsyncRequest = BaseVideoOutputRequest

// VideoMuxAudioRequest Exactly one of output_path / output_url required in sync mode; both optional in async mode (auto-staged).
type VideoMuxAudioRequest = BaseVideoOutputRequest

// VideoRestoreRequest defines model for VideoRestoreRequest.
type VideoRestoreRequest struct {
	AsyncJob *bool `json:"async_job,omitempty"`

	// FilePath FILES_DIR-relative path of an already-uploaded video.
	FilePath *string `json:"file_path"`

	// FileUrl HTTP(S) URL the server fetches.
	FileUrl      *string                          `json:"file_url"`
	OutputFormat *VideoRestoreRequestOutputFormat `json:"output_format,omitempty"`
	OutputPath   *string                          `json:"output_path"`
	OutputUrl    *string                          `json:"output_url"`

	// WebhookUrl Notify URL on async completion (HMAC-signed).
	WebhookUrl *string `json:"webhook_url"`
}

// VideoRestoreRequestOutputFormat defines model for VideoRestoreRequest.OutputFormat.
type VideoRestoreRequestOutputFormat string

// VideoScaleRequest defines model for VideoScaleRequest.
type VideoScaleRequest struct {
	AsyncJob *bool `json:"async_job,omitempty"`

	// FilePath FILES_DIR-relative path of an already-uploaded video.
	FilePath *string `json:"file_path"`

	// FileUrl HTTP(S) URL the server fetches.
	FileUrl      *string                        `json:"file_url"`
	OutputFormat *VideoScaleRequestOutputFormat `json:"output_format,omitempty"`
	OutputPath   *string                        `json:"output_path"`
	OutputUrl    *string                        `json:"output_url"`

	// WebhookUrl Notify URL on async completion (HMAC-signed).
	WebhookUrl *string `json:"webhook_url"`
}

// VideoScaleRequestOutputFormat defines model for VideoScaleRequest.OutputFormat.
type VideoScaleRequestOutputFormat string

// VideoThumbnailGridRequest Exactly one of file_path / file_url MUST be provided. Enforced at handler boundary.
type VideoThumbnailGridRequest = BaseVideoInputRequest

// VideoTranscodeRequest defines model for VideoTranscodeRequest.
type VideoTranscodeRequest struct {
	AsyncJob *bool `json:"async_job,omitempty"`

	// FilePath FILES_DIR-relative path of an already-uploaded video.
	FilePath *string `json:"file_path"`

	// FileUrl HTTP(S) URL the server fetches.
	FileUrl      *string                            `json:"file_url"`
	OutputFormat *VideoTranscodeRequestOutputFormat `json:"output_format,omitempty"`
	OutputPath   *string                            `json:"output_path"`
	OutputUrl    *string                            `json:"output_url"`

	// WebhookUrl Notify URL on async completion (HMAC-signed).
	WebhookUrl *string `json:"webhook_url"`
}

// VideoTranscodeRequestOutputFormat defines model for VideoTranscodeRequest.OutputFormat.
type VideoTranscodeRequestOutputFormat string

// VideoTrimRequest defines model for VideoTrimRequest.
type VideoTrimRequest struct {
	AsyncJob *bool `json:"async_job,omitempty"`

	// FilePath FILES_DIR-relative path of an already-uploaded video.
	FilePath *string `json:"file_path"`

	// FileUrl HTTP(S) URL the server fetches.
	FileUrl      *string                       `json:"file_url"`
	OutputFormat *VideoTrimRequestOutputFormat `json:"output_format,omitempty"`
	OutputPath   *string                       `json:"output_path"`
	OutputUrl    *string                       `json:"output_url"`

	// WebhookUrl Notify URL on async completion (HMAC-signed).
	WebhookUrl *string `json:"webhook_url"`
}

// VideoTrimRequestOutputFormat defines model for VideoTrimRequest.OutputFormat.
type VideoTrimRequestOutputFormat string

// EngineSlug defines model for EngineSlug.
type EngineSlug = string

// FilesPath defines model for FilesPath.
type FilesPath = string

// JobIdPath defines model for JobIdPath.
type JobIdPath = string

// N400 defines model for 400.
type N400 = ErrorBody

// N401 defines model for 401.
type N401 = ErrorBody

// N403 defines model for 403.
type N403 = ErrorBody

// N404 defines model for 404.
type N404 = ErrorBody

// N413 defines model for 413.
type N413 = ErrorBody

// N422 defines model for 422.
type N422 = ErrorBody

// PostVideoConcatJSONRequestBody defines body for PostVideoConcat for application/json ContentType.
type PostVideoConcatJSONRequestBody = VideoConcatRequest

// PostVideoExtractAudioJSONRequestBody defines body for PostVideoExtractAudio for application/json ContentType.
type PostVideoExtractAudioJSONRequestBody = VideoExtractAudioRequest

// PostVideoInfoJSONRequestBody defines body for PostVideoInfo for application/json ContentType.
type PostVideoInfoJSONRequestBody = VideoInfoRequest

// PostVideoLipsyncJSONRequestBody defines body for PostVideoLipsync for application/json ContentType.
type PostVideoLipsyncJSONRequestBody = VideoLipsyncRequest

// PostVideoMuxAudioJSONRequestBody defines body for PostVideoMuxAudio for application/json ContentType.
type PostVideoMuxAudioJSONRequestBody = VideoMuxAudioRequest

// PostVideoRestoreJSONRequestBody defines body for PostVideoRestore for application/json ContentType.
type PostVideoRestoreJSONRequestBody = VideoRestoreRequest

// PostVideoScaleJSONRequestBody defines body for PostVideoScale for application/json ContentType.
type PostVideoScaleJSONRequestBody = VideoScaleRequest

// PostVideoThumbnailGridJSONRequestBody defines body for PostVideoThumbnailGrid for application/json ContentType.
type PostVideoThumbnailGridJSONRequestBody = VideoThumbnailGridRequest

// PostVideoTranscodeJSONRequestBody defines body for PostVideoTranscode for application/json ContentType.
type PostVideoTranscodeJSONRequestBody = VideoTranscodeRequest

// PostVideoTrimJSONRequestBody defines body for PostVideoTrim for application/json ContentType.
type PostVideoTrimJSONRequestBody = VideoTrimRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListEngines request
	ListEngines(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// EvictEngine request
	EvictEngine(ctx context.Context, slug EngineSlug, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteFile request
	DeleteFile(ctx context.Context, path FilesPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetFile request
	GetFile(ctx context.Context, path FilesPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutFileWithBody request with any body
	PutFileWithBody(ctx context.Context, path FilesPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetJob request
	GetJob(ctx context.Context, jobId JobIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostVideoConcatWithBody request with any body
	PostVideoConcatWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostVideoConcat(ctx context.Context, body PostVideoConcatJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostVideoExtractAudioWithBody request with any body
	PostVideoExtractAudioWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostVideoExtractAudio(ctx context.Context, body PostVideoExtractAudioJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostVideoInfoWithBody request with any body
	PostVideoInfoWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostVideoInfo(ctx context.Context, body PostVideoInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostVideoLipsyncWithBody request with any body
	PostVideoLipsyncWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostVideoLipsync(ctx context.Context, body PostVideoLipsyncJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostVideoMuxAudioWithBody request with any body
	PostVideoMuxAudioWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostVideoMuxAudio(ctx context.Context, body PostVideoMuxAudioJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostVideoRestoreWithBody request with any body
	PostVideoRestoreWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostVideoRestore(ctx context.Context, body PostVideoRestoreJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostVideoScaleWithBody request with any body
	PostVideoScaleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostVideoScale(ctx context.Context, body PostVideoScaleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostVideoThumbnailGridWithBody request with any body
	PostVideoThumbnailGridWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostVideoThumbnailGrid(ctx context.Context, body PostVideoThumbnailGridJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostVideoTranscodeWithBody request with any body
	PostVideoTranscodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostVideoTranscode(ctx context.Context, body PostVideoTranscodeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostVideoTrimWithBody request with any body
	PostVideoTrimWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostVideoTrim(ctx context.Context, body PostVideoTrimJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListEngines(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListEnginesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EvictEngine(ctx context.Context, slug EngineSlug, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEvictEngineRequest(c.Server, slug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteFile(ctx context.Context, path FilesPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteFileRequest(c.Server, path)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetFile(ctx context.Context, path FilesPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetFileRequest(c.Server, path)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutFileWithBody(ctx context.Context, path FilesPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutFileRequestWithBody(c.Server, path, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetJob(ctx context.Context, jobId JobIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoConcatWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoConcatRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoConcat(ctx context.Context, body PostVideoConcatJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoConcatRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoExtractAudioWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoExtractAudioRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoExtractAudio(ctx context.Context, body PostVideoExtractAudioJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoExtractAudioRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoInfoWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoInfoRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoInfo(ctx context.Context, body PostVideoInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoInfoRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoLipsyncWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoLipsyncRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoLipsync(ctx context.Context, body PostVideoLipsyncJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoLipsyncRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoMuxAudioWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoMuxAudioRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoMuxAudio(ctx context.Context, body PostVideoMuxAudioJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoMuxAudioRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoRestoreWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoRestoreRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoRestore(ctx context.Context, body PostVideoRestoreJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoRestoreRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoScaleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoScaleRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoScale(ctx context.Context, body PostVideoScaleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoScaleRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoThumbnailGridWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoThumbnailGridRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoThumbnailGrid(ctx context.Context, body PostVideoThumbnailGridJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoThumbnailGridRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoTranscodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoTranscodeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoTranscode(ctx context.Context, body PostVideoTranscodeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoTranscodeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoTrimWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoTrimRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVideoTrim(ctx context.Context, body PostVideoTrimJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVideoTrimRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListEnginesRequest generates requests for ListEngines
func NewListEnginesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/engines")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewEvictEngineRequest generates requests for EvictEngine
func NewEvictEngineRequest(server string, slug EngineSlug) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "slug", runtime.ParamLocationPath, slug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/engines/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteFileRequest generates requests for DeleteFile
func NewDeleteFileRequest(server string, path FilesPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "path", runtime.ParamLocationPath, path)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/files/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetFileRequest generates requests for GetFile
func NewGetFileRequest(server string, path FilesPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "path", runtime.ParamLocationPath, path)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/files/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutFileRequestWithBody generates requests for PutFile with any type of body
func NewPutFileRequestWithBody(server string, path FilesPath, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "path", runtime.ParamLocationPath, path)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/files/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetJobRequest generates requests for GetJob
func NewGetJobRequest(server string, jobId JobIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "job_id", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostVideoConcatRequest calls the generic PostVideoConcat builder with application/json body
func NewPostVideoConcatRequest(server string, body PostVideoConcatJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostVideoConcatRequestWithBody(server, "application/json", bodyReader)
}

// NewPostVideoConcatRequestWithBody generates requests for PostVideoConcat with any type of body
func NewPostVideoConcatRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/video/concat")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostVideoExtractAudioRequest calls the generic PostVideoExtractAudio builder with application/json body
func NewPostVideoExtractAudioRequest(server string, body PostVideoExtractAudioJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostVideoExtractAudioRequestWithBody(server, "application/json", bodyReader)
}

// NewPostVideoExtractAudioRequestWithBody generates requests for PostVideoExtractAudio with any type of body
func NewPostVideoExtractAudioRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/video/extract_audio")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostVideoInfoRequest calls the generic PostVideoInfo builder with application/json body
func NewPostVideoInfoRequest(server string, body PostVideoInfoJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostVideoInfoRequestWithBody(server, "application/json", bodyReader)
}

// NewPostVideoInfoRequestWithBody generates requests for PostVideoInfo with any type of body
func NewPostVideoInfoRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/video/info")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostVideoLipsyncRequest calls the generic PostVideoLipsync builder with application/json body
func NewPostVideoLipsyncRequest(server string, body PostVideoLipsyncJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostVideoLipsyncRequestWithBody(server, "application/json", bodyReader)
}

// NewPostVideoLipsyncRequestWithBody generates requests for PostVideoLipsync with any type of body
func NewPostVideoLipsyncRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/video/lipsync")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostVideoMuxAudioRequest calls the generic PostVideoMuxAudio builder with application/json body
func NewPostVideoMuxAudioRequest(server string, body PostVideoMuxAudioJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostVideoMuxAudioRequestWithBody(server, "application/json", bodyReader)
}

// NewPostVideoMuxAudioRequestWithBody generates requests for PostVideoMuxAudio with any type of body
func NewPostVideoMuxAudioRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/video/mux_audio")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostVideoRestoreRequest calls the generic PostVideoRestore builder with application/json body
func NewPostVideoRestoreRequest(server string, body PostVideoRestoreJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostVideoRestoreRequestWithBody(server, "application/json", bodyReader)
}

// NewPostVideoRestoreRequestWithBody generates requests for PostVideoRestore with any type of body
func NewPostVideoRestoreRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/video/restore")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostVideoScaleRequest calls the generic PostVideoScale builder with application/json body
func NewPostVideoScaleRequest(server string, body PostVideoScaleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostVideoScaleRequestWithBody(server, "application/json", bodyReader)
}

// NewPostVideoScaleRequestWithBody generates requests for PostVideoScale with any type of body
func NewPostVideoScaleRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/video/scale")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostVideoThumbnailGridRequest calls the generic PostVideoThumbnailGrid builder with application/json body
func NewPostVideoThumbnailGridRequest(server string, body PostVideoThumbnailGridJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostVideoThumbnailGridRequestWithBody(server, "application/json", bodyReader)
}

// NewPostVideoThumbnailGridRequestWithBody generates requests for PostVideoThumbnailGrid with any type of body
func NewPostVideoThumbnailGridRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/video/thumbnail_grid")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostVideoTranscodeRequest calls the generic PostVideoTranscode builder with application/json body
func NewPostVideoTranscodeRequest(server string, body PostVideoTranscodeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostVideoTranscodeRequestWithBody(server, "application/json", bodyReader)
}

// NewPostVideoTranscodeRequestWithBody generates requests for PostVideoTranscode with any type of body
func NewPostVideoTranscodeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/video/transcode")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostVideoTrimRequest calls the generic PostVideoTrim builder with application/json body
func NewPostVideoTrimRequest(server string, body PostVideoTrimJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostVideoTrimRequestWithBody(server, "application/json", bodyReader)
}

// NewPostVideoTrimRequestWithBody generates requests for PostVideoTrim with any type of body
func NewPostVideoTrimRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/video/trim")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListEnginesWithResponse request
	ListEnginesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListEnginesHTTPResponse, error)

	// EvictEngineWithResponse request
	EvictEngineWithResponse(ctx context.Context, slug EngineSlug, reqEditors ...RequestEditorFn) (*EvictEngineHTTPResponse, error)

	// DeleteFileWithResponse request
	DeleteFileWithResponse(ctx context.Context, path FilesPath, reqEditors ...RequestEditorFn) (*DeleteFileHTTPResponse, error)

	// GetFileWithResponse request
	GetFileWithResponse(ctx context.Context, path FilesPath, reqEditors ...RequestEditorFn) (*GetFileHTTPResponse, error)

	// PutFileWithBodyWithResponse request with any body
	PutFileWithBodyWithResponse(ctx context.Context, path FilesPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutFileHTTPResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthHTTPResponse, error)

	// GetJobWithResponse request
	GetJobWithResponse(ctx context.Context, jobId JobIdPath, reqEditors ...RequestEditorFn) (*GetJobHTTPResponse, error)

	// PostVideoConcatWithBodyWithResponse request with any body
	PostVideoConcatWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoConcatHTTPResponse, error)

	PostVideoConcatWithResponse(ctx context.Context, body PostVideoConcatJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoConcatHTTPResponse, error)

	// PostVideoExtractAudioWithBodyWithResponse request with any body
	PostVideoExtractAudioWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoExtractAudioHTTPResponse, error)

	PostVideoExtractAudioWithResponse(ctx context.Context, body PostVideoExtractAudioJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoExtractAudioHTTPResponse, error)

	// PostVideoInfoWithBodyWithResponse request with any body
	PostVideoInfoWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoInfoHTTPResponse, error)

	PostVideoInfoWithResponse(ctx context.Context, body PostVideoInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoInfoHTTPResponse, error)

	// PostVideoLipsyncWithBodyWithResponse request with any body
	PostVideoLipsyncWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoLipsyncHTTPResponse, error)

	PostVideoLipsyncWithResponse(ctx context.Context, body PostVideoLipsyncJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoLipsyncHTTPResponse, error)

	// PostVideoMuxAudioWithBodyWithResponse request with any body
	PostVideoMuxAudioWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoMuxAudioHTTPResponse, error)

	PostVideoMuxAudioWithResponse(ctx context.Context, body PostVideoMuxAudioJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoMuxAudioHTTPResponse, error)

	// PostVideoRestoreWithBodyWithResponse request with any body
	PostVideoRestoreWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoRestoreHTTPResponse, error)

	PostVideoRestoreWithResponse(ctx context.Context, body PostVideoRestoreJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoRestoreHTTPResponse, error)

	// PostVideoScaleWithBodyWithResponse request with any body
	PostVideoScaleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoScaleHTTPResponse, error)

	PostVideoScaleWithResponse(ctx context.Context, body PostVideoScaleJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoScaleHTTPResponse, error)

	// PostVideoThumbnailGridWithBodyWithResponse request with any body
	PostVideoThumbnailGridWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoThumbnailGridHTTPResponse, error)

	PostVideoThumbnailGridWithResponse(ctx context.Context, body PostVideoThumbnailGridJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoThumbnailGridHTTPResponse, error)

	// PostVideoTranscodeWithBodyWithResponse request with any body
	PostVideoTranscodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoTranscodeHTTPResponse, error)

	PostVideoTranscodeWithResponse(ctx context.Context, body PostVideoTranscodeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoTranscodeHTTPResponse, error)

	// PostVideoTrimWithBodyWithResponse request with any body
	PostVideoTrimWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoTrimHTTPResponse, error)

	PostVideoTrimWithResponse(ctx context.Context, body PostVideoTrimJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoTrimHTTPResponse, error)
}

type ListEnginesHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EngineList
	JSON401      *N401
}

// Status returns HTTPResponse.Status
func (r ListEnginesHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListEnginesHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type EvictEngineHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *N401
	JSON404      *N404
}

// Status returns HTTPResponse.Status
func (r EvictEngineHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EvictEngineHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteFileHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *N401
	JSON404      *N404
}

// Status returns HTTPResponse.Status
func (r DeleteFileHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteFileHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetFileHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *N401
	JSON404      *N404
}

// Status returns HTTPResponse.Status
func (r GetFileHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetFileHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutFileHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *StagedOutputResponse
	JSON401      *N401
	JSON413      *N413
}

// Status returns HTTPResponse.Status
func (r PutFileHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutFileHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetJobHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JobStatusResponse
	JSON401      *N401
	JSON404      *N404
}

// Status returns HTTPResponse.Status
func (r GetJobHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostVideoConcatHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r PostVideoConcatHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostVideoConcatHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostVideoExtractAudioHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r PostVideoExtractAudioHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostVideoExtractAudioHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostVideoInfoHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VideoInfoResponse
	JSON400      *N400
	JSON401      *N401
}

// Status returns HTTPResponse.Status
func (r PostVideoInfoHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostVideoInfoHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostVideoLipsyncHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
	JSON202 *JobAcceptedResponse
	JSON400 *N400
	JSON401 *N401
	JSON403 *N403
	JSON422 *N422
}

// Status returns HTTPResponse.Status
func (r PostVideoLipsyncHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostVideoLipsyncHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostVideoMuxAudioHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r PostVideoMuxAudioHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostVideoMuxAudioHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostVideoRestoreHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
	JSON202 *JobAcceptedResponse
	JSON400 *N400
	JSON401 *N401
	JSON422 *N422
}

// Status returns HTTPResponse.Status
func (r PostVideoRestoreHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostVideoRestoreHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostVideoScaleHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r PostVideoScaleHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostVideoScaleHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostVideoThumbnailGridHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r PostVideoThumbnailGridHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostVideoThumbnailGridHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostVideoTranscodeHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r PostVideoTranscodeHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostVideoTranscodeHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostVideoTrimHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
	JSON400 *N400
	JSON422 *N422
}

// Status returns HTTPResponse.Status
func (r PostVideoTrimHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostVideoTrimHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListEnginesWithResponse request returning *ListEnginesHTTPResponse
func (c *ClientWithResponses) ListEnginesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListEnginesHTTPResponse, error) {
	rsp, err := c.ListEngines(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListEnginesHTTPResponse(rsp)
}

// EvictEngineWithResponse request returning *EvictEngineHTTPResponse
func (c *ClientWithResponses) EvictEngineWithResponse(ctx context.Context, slug EngineSlug, reqEditors ...RequestEditorFn) (*EvictEngineHTTPResponse, error) {
	rsp, err := c.EvictEngine(ctx, slug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEvictEngineHTTPResponse(rsp)
}

// DeleteFileWithResponse request returning *DeleteFileHTTPResponse
func (c *ClientWithResponses) DeleteFileWithResponse(ctx context.Context, path FilesPath, reqEditors ...RequestEditorFn) (*DeleteFileHTTPResponse, error) {
	rsp, err := c.DeleteFile(ctx, path, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteFileHTTPResponse(rsp)
}

// GetFileWithResponse request returning *GetFileHTTPResponse
func (c *ClientWithResponses) GetFileWithResponse(ctx context.Context, path FilesPath, reqEditors ...RequestEditorFn) (*GetFileHTTPResponse, error) {
	rsp, err := c.GetFile(ctx, path, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetFileHTTPResponse(rsp)
}

// PutFileWithBodyWithResponse request with arbitrary body returning *PutFileHTTPResponse
func (c *ClientWithResponses) PutFileWithBodyWithResponse(ctx context.Context, path FilesPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutFileHTTPResponse, error) {
	rsp, err := c.PutFileWithBody(ctx, path, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutFileHTTPResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthHTTPResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthHTTPResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthHTTPResponse(rsp)
}

// GetJobWithResponse request returning *GetJobHTTPResponse
func (c *ClientWithResponses) GetJobWithResponse(ctx context.Context, jobId JobIdPath, reqEditors ...RequestEditorFn) (*GetJobHTTPResponse, error) {
	rsp, err := c.GetJob(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobHTTPResponse(rsp)
}

// PostVideoConcatWithBodyWithResponse request with arbitrary body returning *PostVideoConcatHTTPResponse
func (c *ClientWithResponses) PostVideoConcatWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoConcatHTTPResponse, error) {
	rsp, err := c.PostVideoConcatWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoConcatHTTPResponse(rsp)
}

func (c *ClientWithResponses) PostVideoConcatWithResponse(ctx context.Context, body PostVideoConcatJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoConcatHTTPResponse, error) {
	rsp, err := c.PostVideoConcat(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoConcatHTTPResponse(rsp)
}

// PostVideoExtractAudioWithBodyWithResponse request with arbitrary body returning *PostVideoExtractAudioHTTPResponse
func (c *ClientWithResponses) PostVideoExtractAudioWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoExtractAudioHTTPResponse, error) {
	rsp, err := c.PostVideoExtractAudioWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoExtractAudioHTTPResponse(rsp)
}

func (c *ClientWithResponses) PostVideoExtractAudioWithResponse(ctx context.Context, body PostVideoExtractAudioJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoExtractAudioHTTPResponse, error) {
	rsp, err := c.PostVideoExtractAudio(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoExtractAudioHTTPResponse(rsp)
}

// PostVideoInfoWithBodyWithResponse request with arbitrary body returning *PostVideoInfoHTTPResponse
func (c *ClientWithResponses) PostVideoInfoWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoInfoHTTPResponse, error) {
	rsp, err := c.PostVideoInfoWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoInfoHTTPResponse(rsp)
}

func (c *ClientWithResponses) PostVideoInfoWithResponse(ctx context.Context, body PostVideoInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoInfoHTTPResponse, error) {
	rsp, err := c.PostVideoInfo(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoInfoHTTPResponse(rsp)
}

// PostVideoLipsyncWithBodyWithResponse request with arbitrary body returning *PostVideoLipsyncHTTPResponse
func (c *ClientWithResponses) PostVideoLipsyncWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoLipsyncHTTPResponse, error) {
	rsp, err := c.PostVideoLipsyncWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoLipsyncHTTPResponse(rsp)
}

func (c *ClientWithResponses) PostVideoLipsyncWithResponse(ctx context.Context, body PostVideoLipsyncJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoLipsyncHTTPResponse, error) {
	rsp, err := c.PostVideoLipsync(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoLipsyncHTTPResponse(rsp)
}

// PostVideoMuxAudioWithBodyWithResponse request with arbitrary body returning *PostVideoMuxAudioHTTPResponse
func (c *ClientWithResponses) PostVideoMuxAudioWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoMuxAudioHTTPResponse, error) {
	rsp, err := c.PostVideoMuxAudioWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoMuxAudioHTTPResponse(rsp)
}

func (c *ClientWithResponses) PostVideoMuxAudioWithResponse(ctx context.Context, body PostVideoMuxAudioJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoMuxAudioHTTPResponse, error) {
	rsp, err := c.PostVideoMuxAudio(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoMuxAudioHTTPResponse(rsp)
}

// PostVideoRestoreWithBodyWithResponse request with arbitrary body returning *PostVideoRestoreHTTPResponse
func (c *ClientWithResponses) PostVideoRestoreWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoRestoreHTTPResponse, error) {
	rsp, err := c.PostVideoRestoreWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoRestoreHTTPResponse(rsp)
}

func (c *ClientWithResponses) PostVideoRestoreWithResponse(ctx context.Context, body PostVideoRestoreJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoRestoreHTTPResponse, error) {
	rsp, err := c.PostVideoRestore(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoRestoreHTTPResponse(rsp)
}

// PostVideoScaleWithBodyWithResponse request with arbitrary body returning *PostVideoScaleHTTPResponse
func (c *ClientWithResponses) PostVideoScaleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoScaleHTTPResponse, error) {
	rsp, err := c.PostVideoScaleWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoScaleHTTPResponse(rsp)
}

func (c *ClientWithResponses) PostVideoScaleWithResponse(ctx context.Context, body PostVideoScaleJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoScaleHTTPResponse, error) {
	rsp, err := c.PostVideoScale(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoScaleHTTPResponse(rsp)
}

// PostVideoThumbnailGridWithBodyWithResponse request with arbitrary body returning *PostVideoThumbnailGridHTTPResponse
func (c *ClientWithResponses) PostVideoThumbnailGridWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoThumbnailGridHTTPResponse, error) {
	rsp, err := c.PostVideoThumbnailGridWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoThumbnailGridHTTPResponse(rsp)
}

func (c *ClientWithResponses) PostVideoThumbnailGridWithResponse(ctx context.Context, body PostVideoThumbnailGridJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoThumbnailGridHTTPResponse, error) {
	rsp, err := c.PostVideoThumbnailGrid(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoThumbnailGridHTTPResponse(rsp)
}

// PostVideoTranscodeWithBodyWithResponse request with arbitrary body returning *PostVideoTranscodeHTTPResponse
func (c *ClientWithResponses) PostVideoTranscodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoTranscodeHTTPResponse, error) {
	rsp, err := c.PostVideoTranscodeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoTranscodeHTTPResponse(rsp)
}

func (c *ClientWithResponses) PostVideoTranscodeWithResponse(ctx context.Context, body PostVideoTranscodeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoTranscodeHTTPResponse, error) {
	rsp, err := c.PostVideoTranscode(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoTranscodeHTTPResponse(rsp)
}

// PostVideoTrimWithBodyWithResponse request with arbitrary body returning *PostVideoTrimHTTPResponse
func (c *ClientWithResponses) PostVideoTrimWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVideoTrimHTTPResponse, error) {
	rsp, err := c.PostVideoTrimWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoTrimHTTPResponse(rsp)
}

func (c *ClientWithResponses) PostVideoTrimWithResponse(ctx context.Context, body PostVideoTrimJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVideoTrimHTTPResponse, error) {
	rsp, err := c.PostVideoTrim(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVideoTrimHTTPResponse(rsp)
}

// ParseListEnginesHTTPResponse parses an HTTP response from a ListEnginesWithResponse call
func ParseListEnginesHTTPResponse(rsp *http.Response) (*ListEnginesHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListEnginesHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EngineList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseEvictEngineHTTPResponse parses an HTTP response from a EvictEngineWithResponse call
func ParseEvictEngineHTTPResponse(rsp *http.Response) (*EvictEngineHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EvictEngineHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseDeleteFileHTTPResponse parses an HTTP response from a DeleteFileWithResponse call
func ParseDeleteFileHTTPResponse(rsp *http.Response) (*DeleteFileHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteFileHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetFileHTTPResponse parses an HTTP response from a GetFileWithResponse call
func ParseGetFileHTTPResponse(rsp *http.Response) (*GetFileHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetFileHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePutFileHTTPResponse parses an HTTP response from a PutFileWithResponse call
func ParsePutFileHTTPResponse(rsp *http.Response) (*PutFileHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutFileHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest StagedOutputResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest N413
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	}

	return response, nil
}

// ParseGetHealthHTTPResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthHTTPResponse(rsp *http.Response) (*GetHealthHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetJobHTTPResponse parses an HTTP response from a GetJobWithResponse call
func ParseGetJobHTTPResponse(rsp *http.Response) (*GetJobHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePostVideoConcatHTTPResponse parses an HTTP response from a PostVideoConcatWithResponse call
func ParsePostVideoConcatHTTPResponse(rsp *http.Response) (*PostVideoConcatHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostVideoConcatHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostVideoExtractAudioHTTPResponse parses an HTTP response from a PostVideoExtractAudioWithResponse call
func ParsePostVideoExtractAudioHTTPResponse(rsp *http.Response) (*PostVideoExtractAudioHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostVideoExtractAudioHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostVideoInfoHTTPResponse parses an HTTP response from a PostVideoInfoWithResponse call
func ParsePostVideoInfoHTTPResponse(rsp *http.Response) (*PostVideoInfoHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostVideoInfoHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VideoInfoResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParsePostVideoLipsyncHTTPResponse parses an HTTP response from a PostVideoLipsyncWithResponse call
func ParsePostVideoLipsyncHTTPResponse(rsp *http.Response) (*PostVideoLipsyncHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostVideoLipsyncHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest JobAcceptedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest N422
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParsePostVideoMuxAudioHTTPResponse parses an HTTP response from a PostVideoMuxAudioWithResponse call
func ParsePostVideoMuxAudioHTTPResponse(rsp *http.Response) (*PostVideoMuxAudioHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostVideoMuxAudioHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostVideoRestoreHTTPResponse parses an HTTP response from a PostVideoRestoreWithResponse call
func ParsePostVideoRestoreHTTPResponse(rsp *http.Response) (*PostVideoRestoreHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostVideoRestoreHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest JobAcceptedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest N422
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParsePostVideoScaleHTTPResponse parses an HTTP response from a PostVideoScaleWithResponse call
func ParsePostVideoScaleHTTPResponse(rsp *http.Response) (*PostVideoScaleHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostVideoScaleHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostVideoThumbnailGridHTTPResponse parses an HTTP response from a PostVideoThumbnailGridWithResponse call
func ParsePostVideoThumbnailGridHTTPResponse(rsp *http.Response) (*PostVideoThumbnailGridHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostVideoThumbnailGridHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostVideoTranscodeHTTPResponse parses an HTTP response from a PostVideoTranscodeWithResponse call
func ParsePostVideoTranscodeHTTPResponse(rsp *http.Response) (*PostVideoTranscodeHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostVideoTranscodeHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostVideoTrimHTTPResponse parses an HTTP response from a PostVideoTrimWithResponse call
func ParsePostVideoTrimHTTPResponse(rsp *http.Response) (*PostVideoTrimHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostVideoTrimHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest N422
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
